on: [push]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{secrets.DEPLOY_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependency
        run: |
          install.packages(c("devtools", "rsconnect", "DBI", "glue", "lubridate", "shiny", "shinyalert", "shinyjs", "blastula", "config", "RMySQL", "dplyr", "bslib", "shinycssloaders"), type = "binary")
          devtools::install_github("shahronak47/shinyRatings")
        shell: Rscript {0}
      - name: shinyapps deploy
        run: |
             rsconnect::setAccountInfo(name='shahronak', token='${{secrets.SHINYAPPS_TOKEN}}', secret='${{secrets.SHINYAPPS_SECRET}}')
             rsconnect::deployApp(appName = 'packagerevieweR',account = 'shahronak', server = 'shinyapps.io', forceUpdate = TRUE)
        shell: Rscript {0}
